version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependabot: lang : github actions"
      - "dependabot: dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependabot: lang : python"
      - "dependabot: dependencies"
